/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HireRouteImport } from './routes/hire'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ApiPublicNotifyRouteImport } from './routes/api/public/notify'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRoute = HireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicNotifyRoute = ApiPublicNotifyRouteImport.update({
  id: '/api/public/notify',
  path: '/api/public/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/learn': typeof LearnRoute
  '/shop': typeof ShopRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/learn': typeof LearnRoute
  '/shop': typeof ShopRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/explore': typeof ExploreRoute
  '/gallery': typeof GalleryRoute
  '/hire': typeof HireRoute
  '/jobs': typeof JobsRoute
  '/learn': typeof LearnRoute
  '/shop': typeof ShopRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/public/notify': typeof ApiPublicNotifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/explore'
    | '/gallery'
    | '/hire'
    | '/jobs'
    | '/learn'
    | '/shop'
    | '/profile'
    | '/api/public/notify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/explore'
    | '/gallery'
    | '/hire'
    | '/jobs'
    | '/learn'
    | '/shop'
    | '/profile'
    | '/api/public/notify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/blogs'
    | '/explore'
    | '/gallery'
    | '/hire'
    | '/jobs'
    | '/learn'
    | '/shop'
    | '/_authenticated/profile'
    | '/api/public/notify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BlogsRoute: typeof BlogsRoute
  ExploreRoute: typeof ExploreRoute
  GalleryRoute: typeof GalleryRoute
  HireRoute: typeof HireRoute
  JobsRoute: typeof JobsRoute
  LearnRoute: typeof LearnRoute
  ShopRoute: typeof ShopRoute
  ApiPublicNotifyRoute: typeof ApiPublicNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/notify': {
      id: '/api/public/notify'
      path: '/api/public/notify'
      fullPath: '/api/public/notify'
      preLoaderRoute: typeof ApiPublicNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BlogsRoute: BlogsRoute,
  ExploreRoute: ExploreRoute,
  GalleryRoute: GalleryRoute,
  HireRoute: HireRoute,
  JobsRoute: JobsRoute,
  LearnRoute: LearnRoute,
  ShopRoute: ShopRoute,
  ApiPublicNotifyRoute: ApiPublicNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
